org: alphaprime8
app: d3-studio
service: DsAPI

frameworkVersion: '3'

package:
  exclude:
    - ./venv/**
    - ./__pycache__/**
    - ./node_modules/**

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'


plugins:
  - serverless-wsgi
  - serverless-python-requirements
